version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            docker-compose -p e2eproject -f ./docker-compose.e2e.yml up --abort-on-container-exit --exit-code-from e2e
            code=$?
            docker-compose -p e2eproject down
            echo $code
            exit $code

