version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            docker-compose -p e2eproject -f ./docker-compose.e2e.yml up e2e
            docker ps -aqf "name=e2e"
            code=$(docker ps -aqf "name=e2e")
            docker-compose -p e2eproject down
            echo $code

