version: 2.1

jobs:
  validate:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Does docker even exist
          command: docker -v
      - run:
          name: Install docker-compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Start containers
          command: docker-compose -p e2e -f ./docker-compose.e2e.yml up e2e

workflows:
  validate-workflow:
    jobs:
      - validate