version: 2.1

jobs:
  checkout:
    steps:
      - checkout
  validate:
    steps:
      - run:
        name: Run test
        command: |
          docker-compose -p e2e -f ./docker-compose.e2e.yml up e2e

workflows:
  validate-workflow:
    jobs:
      - checkout
      - validate